# Generated by Django 5.0.2 on 2024-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('desc', models.TextField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('student_name', models.CharField(max_length=10)),
                ('student_result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('experience', models.TextField(max_length=50)),
                ('about', models.TextField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
