# Generated by Django 5.0.2 on 2024-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
